### ISSUE TITLE
ask for available rocSHMEM env configuration

### ISSUE THREAD

**Issue by hongbilu** [ROCm-Developer-Tools/ROC_SHMEM#2]
We are trying to setup rocSHMEM environment in our servers, but cannot get available rocSHMEM env configuration for working well.
   Could you tell us an available configuration you have run?
   Ubuntu version: 
   Linux kernel version:
   Rocshmem version:
   Rocm version:
   MLX ofed version:
   MLX hardware:
   AMD card hardware:

**Comment by BKP** [comment]
We have an upcoming release tentatively targeting the following:
Ubuntu version: Ubuntu 20.04.2 LTS
Linux kernel version: 5.11.0-27-generic
Rocshmem version: 1.3
Rocm version: 4.4 or 4.5
MLX OFED version: 5.4.1
MLX hardware: MT27700 Family [ConnectX-4] and MT28908 Family [ConnectX-6]
AMD care hardware: MI25, MI50, MI100, MI200

**Comment by hongbilu** [comment]
very appreciate and very excited for new release
