### ISSUE TITLE
setup ROC_SHMEM on Spock

### ISSUE THREAD

**Issue by nanding0701** [ROCm-Developer-Tools/ROC_SHMEM#3]
Hi, I'm trying to setup ROC_SHMEM on Spock (OLCF). But I got an error which I don't have a clue for it.  Can you provide some guidance on building ROC_SHMEM on Spock?

My error: 
../build_configs/rc_single
-- The CXX compiler identification is Clang 12.0.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/rocm/bin/hipcc - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
CMake Error at /autofs/nccs-svm1_sw/spock/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/cmake-3.20.2-72d3n4vvyfrzgxvj5gzq7lbjuogy6bul/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Ibverbs (missing: IBVERBS_LIBRARY IBVERBS_INCLUDE_DIR)
Call Stack (most recent call first):
  /autofs/nccs-svm1_sw/spock/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/cmake-3.20.2-72d3n4vvyfrzgxvj5gzq7lbjuogy6bul/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindIbverbs.cmake:58 (find_package_handle_standard_args)
  CMakeLists.txt:115 (find_package)

-- Configuring incomplete, errors occurred!
See also "/ccs/home/nanding/mysoftware/ROC_SHMEM/library/build/CMakeFiles/CMakeOutput.log".
gmake: Makefile: No such file or directory
gmake: *** No rule to make target 'Makefile'.  Stop.
CMake Error: Error processing file: /ccs/home/nanding/mysoftware/ROC_SHMEM/library/build/cmake_install.cmake

**Comment by BKP** [comment]
The CMake build infrastructure relies on finding Infiniband verbs.

Within library/CMakeLists.txt, you can see:
find_package(Ibverbs REQUIRED)

This line marks the Ibverbs target as a dependency for a successful build.

Within cmake/Modules/FindIbverbs.cmake, you can see the build infrastructure's attempt to locate the Ibverbs library and Ibverbs headers that are required to compile the library.

To resolve your issue, you need to inform the CMake build infrastructure where to find Ibverbs.

**Comment by BKP** [comment]
Issue resolved.
