### ISSUE TITLE
setup ROC_SHMEMv1.3 examples on Spock

### ISSUE THREAD

**Issue by nanding0701** [ROCm-Developer-Tools/ROC_SHMEM#4]
Hi, I'm trying to install roc_shmem v1.3 on Spock at OLCF. I'm using rocm/4.3.0, and the roc_shmem library is built with rc_multi_wf_coal.

When I build the example (device-init), I got the below linking error:

[100%] Linking CXX executable rocshmem_example_driver
/autofs/nccs-svm1_sw/spock/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/cmake-3.21.2-dev-ovcgpray6yyjz2n7wjuv6lv4qkgietzs/bin/cmake -E cmake_link_script CMakeFiles/rocshmem_examp
le_driver.dir/link.txt --verbose=1
/opt/rocm-4.3.0/llvm/bin/clang++ -O3 -DNDEBUG @CMakeFiles/rocshmem_example_driver.dir/objects1.rsp -o rocshmem_example_driver @CMakeFiles/rocshmem_example_driver.dir/linklibs.rsp
lld: error: undefined hidden symbol: roc_shmem_wg_init()
>>> referenced by lto.tmp:(BarrierAllTest(int, unsigned long*))
>>> referenced by lto.tmp:(BarrierAllTest(int, unsigned long*))
>>> referenced by lto.tmp:(void ReductionTest<float, (ROC_SHMEM_OP)0>(int, int, unsigned long*, float*, float*, float*, long*, int, TestType, int))
>>> referenced 13 more times

lld: error: undefined hidden symbol: roc_shmem_wg_ctx_create(long, unsigned long**)
>>> referenced by lto.tmp:(BarrierAllTest(int, unsigned long*))
>>> referenced by lto.tmp:(BarrierAllTest(int, unsigned long*))
>>> referenced by lto.tmp:(void ReductionTest<float, (ROC_SHMEM_OP)0>(int, int, unsigned long*, float*, float*, float*, long*, int, TestType, int))
>>> referenced 13 more times

lld: error: undefined hidden symbol: roc_shmem_timer()
>>> referenced by lto.tmp:(BarrierAllTest(int, unsigned long*))
>>> referenced by lto.tmp:(BarrierAllTest(int, unsigned long*))
>>> referenced by lto.tmp:(BarrierAllTest(int, unsigned long*))
>>> referenced 29 more times

lld: error: undefined hidden symbol: roc_shmem_ctx_wg_barrier_all(unsigned long*)
>>> referenced by lto.tmp:(BarrierAllTest(int, unsigned long*))
>>> referenced by lto.tmp:(BarrierAllTest(int, unsigned long*))
>>> referenced by lto.tmp:(void ReductionTest<float, (ROC_SHMEM_OP)0>(int, int, unsigned long*, float*, float*, float*, long*, int, TestType, int))
>>> referenced 3 more times

lld: error: undefined hidden symbol: roc_shmem_wg_ctx_destroy(unsigned long*)
>>> referenced by lto.tmp:(BarrierAllTest(int, unsigned long*))
>>> referenced by lto.tmp:(BarrierAllTest(int, unsigned long*))
>>> referenced by lto.tmp:(void ReductionTest<float, (ROC_SHMEM_OP)0>(int, int, unsigned long*, float*, float*, float*, long*, int, TestType, int))
>>> referenced 13 more times

lld: error: undefined hidden symbol: roc_shmem_ctx_putmem_nbi(unsigned long*, void*, void const*, unsigned long, int)
>>> referenced by lto.tmp:(PrimitiveTest(int, int, unsigned long*, char*, char*, int, TestType, int))
>>> referenced by lto.tmp:(PrimitiveTest(int, int, unsigned long*, char*, char*, int, TestType, int))

lld: error: undefined hidden symbol: roc_shmem_ctx_putmem(unsigned long*, void*, void const*, unsigned long, int)
>>> referenced by lto.tmp:(PrimitiveTest(int, int, unsigned long*, char*, char*, int, TestType, int))
>>> referenced by lto.tmp:(PrimitiveTest(int, int, unsigned long*, char*, char*, int, TestType, int))
>>> referenced by lto.tmp:(RandomAccessTest(int, int, unsigned long*, int*, int*, int, OpType, int, int, int, unsigned int*, unsigned int*, unsigned int*, int))
>>> referenced 1 more times

lld: error: undefined hidden symbol: roc_shmem_ctx_getmem_nbi(unsigned long*, void*, void const*, unsigned long, int)
>>> referenced by lto.tmp:(PrimitiveTest(int, int, unsigned long*, char*, char*, int, TestType, int))
>>> referenced by lto.tmp:(PrimitiveTest(int, int, unsigned long*, char*, char*, int, TestType, int))

lld: error: undefined hidden symbol: roc_shmem_ctx_getmem(unsigned long*, void*, void const*, unsigned long, int)
>>> referenced by lto.tmp:(PrimitiveTest(int, int, unsigned long*, char*, char*, int, TestType, int))
>>> referenced by lto.tmp:(PrimitiveTest(int, int, unsigned long*, char*, char*, int, TestType, int))
>>> referenced by lto.tmp:(PrimitiveAMOTest(int, int, unsigned long*, char*, long*, TestType, int))
>>> referenced 5 more times

lld: error: undefined hidden symbol: roc_shmem_ctx_quiet(unsigned long*)
>>> referenced by lto.tmp:(PrimitiveTest(int, int, unsigned long*, char*, char*, int, TestType, int))
>>> referenced by lto.tmp:(PrimitiveTest(int, int, unsigned long*, char*, char*, int, TestType, int))
>>> referenced by lto.tmp:(PrimitiveAMOTest(int, int, unsigned long*, char*, long*, TestType, int))
>>> referenced 3 more times

lld: error: undefined hidden symbol: roc_shmem_ctx_int64_atomic_inc(unsigned long*, long*, int)
>>> referenced by lto.tmp:(PrimitiveAMOTest(int, int, unsigned long*, char*, long*, TestType, int))
>>> referenced by lto.tmp:(PrimitiveAMOTest(int, int, unsigned long*, char*, long*, TestType, int))

lld: error: undefined hidden symbol: roc_shmem_ctx_int64_atomic_add(unsigned long*, long*, long, int)
>>> referenced by lto.tmp:(PrimitiveAMOTest(int, int, unsigned long*, char*, long*, TestType, int))
>>> referenced by lto.tmp:(PrimitiveAMOTest(int, int, unsigned long*, char*, long*, TestType, int))

lld: error: undefined hidden symbol: roc_shmem_ctx_int64_atomic_compare_swap(unsigned long*, long*, long, long, int)
>>> referenced by lto.tmp:(PrimitiveAMOTest(int, int, unsigned long*, char*, long*, TestType, int))
>>> referenced by lto.tmp:(PrimitiveAMOTest(int, int, unsigned long*, char*, long*, TestType, int))

lld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
clang-13: error: amdgcn-link command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [CMakeFiles/rocshmem_example_driver.dir/build.make:251: rocshmem_example_driver] Error 1
gmake[2]: Leaving directory '/autofs/nccs-svm1_home1/nanding/mysoftware/ROC_SHMEM/clients/examples/build_w_rc_multi_wf_coal'
gmake[1]: *** [CMakeFiles/Makefile2:86: CMakeFiles/rocshmem_example_driver.dir/all] Error 2
gmake[1]: Leaving directory '/autofs/nccs-svm1_home1/nanding/mysoftware/ROC_SHMEM/clients/examples/build_w_rc_multi_wf_coal'
gmake: *** [Makefile:94: all] Error 2

My environment setting: 
module list

Currently Loaded Modules:
  1) craype-x86-rome         4) perftools-base/21.05.0                   7) cray-pmi-lib/6.0.12      10) craype/2.7.8      13) cray-libsci/21.06.1.1  16) cmake/3.21.2-dev
  2) libfabric/1.11.0.4.75   5) xpmem/2.2.40-2.1_2.44__g3cf3325.shasta   8) craype-accel-amd-gfx908  11) cray-dsmml/0.1.5  14) PrgEnv-cray/8.1.0      17) tmux/3.1b
  3) craype-network-ofi      6) cray-pmi/6.0.12

**Comment by BKP** [comment]
Just to verify, are you using the builds in the build_configs for the clients as well? There's a "release" build in the folder which invokes CMake on the clients.

There are some specific options which have to be specified when compiling both the library and the client code for it to link properly.

**Comment by BKP** [comment]
Issue resolved. User's environment was locating incorrect compiler.
